"""Generate src/types/entities.ts from the server's C# models (camelCase JSON).

Run from JunctionRelay_Server/:  python3 junctionrelaywebui/scripts/generate-entity-types.py > junctionrelaywebui/src/types/entities.ts
"""
import re, sys
MODELS = {  # C# class -> TS name
 'Model_Sensor':'Sensor','Model_DeviceResponse':'Device','Model_Device_Screens':'DeviceScreen','Model_CollectorResponse':'Collector',
 'Model_Junction':'Junction','Model_ServiceResponse':'Service','Model_JunctionDeviceLink':'JunctionDeviceLink',
 'Model_JunctionCollectorLink':'JunctionCollectorLink','Model_JunctionSensorTarget':'JunctionSensorTarget','Model_EventRule':'EventRule',
 'Model_Payload':'Payload','Model_JunctionScreenLayout':'JunctionScreenLayout','Model_Device_Capabilities':'DeviceCapabilities',
 'Model_Device_I2CDevice':'DeviceI2CDevice','FrameLayoutDto':'FrameLayoutSummary','Model_Device_Info':'DeviceInfo','Model_Layout_Subscription':'LayoutSubscription','Model_Device':'DeviceRecord','Model_Logic':'JunctionLogic','Model_Notifications':'JunctionNotification','Model_EventTrigger':'EventTrigger','Model_EventAction':'EventAction','Model_Device_I2CDevice_Endpoint':'DeviceI2CDeviceEndpoint','Model_Device_Preferences':'DevicePreferencesRecord',
}
PRIM = {'int':'number','long':'number','double':'number','float':'number','decimal':'number','short':'number','byte':'number',
        'string':'string','bool':'boolean','DateTime':'string','DateTimeOffset':'string','Guid':'string','object':'unknown','JsonElement':'unknown'}
src = {}
import glob
for f in glob.glob('Models/**/*.cs', recursive=True) + glob.glob('Controllers/*.cs'):
    s = open(f, encoding='utf-8-sig').read()
    for m in re.finditer(r'public (?:partial )?class (\w+)[^{]*\{', s):
        depth=1; i=m.end()
        while depth and i < len(s):
            depth += {'{':1,'}':-1}.get(s[i],0); i+=1
        src[m.group(1)] = s[m.end():i-1]
def ts_type(t):
    t=t.strip(); nullable=t.endswith('?'); t=t.rstrip('?')
    m=re.fullmatch(r'(?:List|IEnumerable|ICollection|IList|HashSet)<(.+)>|(.+)\[\]', t)
    if m: inner=ts_type(m.group(1) or m.group(2)); r=f'{inner}[]' if ' ' not in inner else f'({inner})[]'
    elif (m:=re.fullmatch(r'(?:Dictionary|IDictionary|IReadOnlyDictionary)<\s*(\w+)\s*,\s*(.+)>', t)): r=f'Record<{ "number" if PRIM.get(m.group(1))=="number" else "string"}, {ts_type(m.group(2))}>'
    elif t in PRIM: r=PRIM[t]
    elif t in MODELS: r=MODELS[t]
    else: r='unknown'
    return r+(' | null' if nullable else '')
def camel(name):
    # System.Text.Json's JsonNamingPolicy.CamelCase: lower the leading run of capitals, but leave the
    # capital that starts the next word (MQTTServiceId -> mqttServiceId, COMPort -> comPort, Id -> id).
    c=list(name)
    for i in range(len(c)):
        if i==1 and not c[i].isupper(): break
        has_next=i+1<len(c)
        if i>0 and has_next and not c[i+1].isupper():
            if c[i+1]==' ': c[i]=c[i].lower()
            break
        c[i]=c[i].lower()
    return ''.join(c)
out=['// GENERATED by scripts/generate-entity-types.py from the server\'s C# models (Models/*.cs) -',
     '// the JSON the API returns, camelCase. Regenerate rather than edit, so the shapes cannot drift.','']
for cs, tsn in MODELS.items():
    body=src.get(cs)
    if body is None: print('missing',cs,file=sys.stderr); continue
    out.append(f'export interface {tsn} {{')
    for m in re.finditer(r'^\s*public\s+(?!static|const|class|enum|override|abstract)([\w<>\[\],\s?]+?)\s+(\w+)\s*(?:\{\s*get\b|\n\s*\{\s*\n?\s*get\b)', body, re.M):
        t,n=m.group(1),m.group(2)
        if '(' in t: continue
        t=re.sub(r'^(?:required|virtual|new)\s+','',t.strip())
        js=camel(n)
        tt=ts_type(t)
        opt='?' if t.strip().endswith('?') else ''
        out.append(f'    {js}{opt}: {tt};')
    out.append('}'); out.append('')
print('\n'.join(out))
