// GENERATED by scripts/generate-entity-types.py from the server's C# models (Models/*.cs) -
// the JSON the API returns, camelCase. Regenerate rather than edit, so the shapes cannot drift.

export interface Sensor {
    id: number;
    originalId: number;
    junctionId?: number | null;
    junctionDeviceLinkId?: number | null;
    junctionCollectorLinkId?: number | null;
    sensorOrder: number;
    mqttServiceId?: number | null;
    mqttTopic?: string | null;
    mqttQoS?: number | null;
    sensorType: string;
    externalId: string;
    deviceName: string;
    name: string;
    componentName: string;
    category: string;
    unit: string;
    value: string;
    decimalPlaces: number;
    sensorTag: string;
    formula?: string | null;
    lastUpdated: string;
    customAttribute1?: string | null;
    customAttribute2?: string | null;
    customAttribute3?: string | null;
    customAttribute4?: string | null;
    customAttribute5?: string | null;
    customAttribute6?: string | null;
    customAttribute7?: string | null;
    customAttribute8?: string | null;
    customAttribute9?: string | null;
    customAttribute10?: string | null;
    isMissing: boolean;
    isStale: boolean;
    isSelected: boolean;
    isVisible: boolean;
    isCustomJunctionSensor: boolean;
    isEventSensor: boolean;
    deviceId?: number | null;
    serviceId?: number | null;
    collectorId?: number | null;
}

export interface Device {
    id: number;
    name: string;
    description: string;
    type: string;
    status: string;
    uniqueIdentifier: string;
    connMode?: string | null;
    comPort?: string | null;
    baudRate?: number | null;
    deviceModel?: string | null;
    deviceManufacturer?: string | null;
    firmwareVersion?: string | null;
    hasCustomFirmware: boolean;
    ignoreUpdates: boolean;
    mcu?: string | null;
    wirelessConnectivity?: string | null;
    flash?: string | null;
    psram?: string | null;
    isConnected: boolean;
    ipAddress?: string | null;
    hasMQTTConfig: boolean;
    httpPort?: number | null;
    webSocketPort?: number | null;
    mqttPort?: number | null;
    hostname?: string | null;
    isGateway: boolean;
    gatewayId?: number | null;
    isJunctionRelayDevice: boolean;
    isCloudDevice: boolean;
    cloudDeviceId?: number | null;
    lastHealthReportAt?: string | null;
    createdAt?: string | null;
    lastHealthAlertSent?: string | null;
    lastHealthReminderSent?: string | null;
    lastUpdated: string;
    pushNotifications: boolean;
    syncMode?: string | null;
    sensors: Sensor[];
    peers: DeviceRecord[];
    pollRate?: number | null;
    sendRate?: number | null;
    sshUsername?: string | null;
    hasSshPassword: boolean;
    externalSshPassword: boolean;
    sshPort?: number | null;
    sshTimeoutMs?: number | null;
    hasSshPrivateKey: boolean;
    externalSshPrivateKey: boolean;
    useSshKeyAuth: boolean;
    sshConnectionRetries?: number | null;
    sshVerifyHostKey: boolean;
    heartbeatProtocol?: string | null;
    heartbeatTarget?: string | null;
    heartbeatExpectedValue?: string | null;
    heartbeatEnabled: boolean;
    heartbeatIntervalMs?: number | null;
    heartbeatGracePeriodMs?: number | null;
    heartbeatMaxRetryAttempts?: number | null;
    useStreamAsHeartbeat: boolean;
    streamHeartbeatThresholdMs?: number | null;
    connectionStatusEnabled: boolean;
    connectionStatusIntervalMs?: number | null;
    lastConnectionStatusCheck?: string | null;
    lastPingAttempt?: string | null;
    lastPinged?: string | null;
    lastPingStatus?: string | null;
    lastPingDurationMs?: number | null;
    consecutivePingFailures?: number | null;
    configLastAppliedAt?: string | null;
    sensorPayloadLastAckAt?: string | null;
    hasOnboardScreen: boolean;
    hasOnboardLED: boolean;
    hasOnboardRGBLED: boolean;
    hasExternalNeopixels: boolean;
    hasExternalMatrix: boolean;
    hasExternalI2CDevices: boolean;
    hasButtons: boolean;
    hasBattery: boolean;
    supportsEthernet: boolean;
    supportsWiFi: boolean;
    supportsBLE: boolean;
    supportsUSB: boolean;
    supportsESPNow: boolean;
    supportsHTTP: boolean;
    supportsMQTT: boolean;
    supportsWebSockets: boolean;
    hasSpeaker: boolean;
    hasMicroSD: boolean;
    isXSD: boolean;
    linkedCollectorId?: number | null;
    screens: DeviceScreen[];
    i2cDevices: DeviceI2CDevice[];
}

export interface DeviceScreen {
    id: number;
    deviceId: number;
    screenKey: string;
    displayName?: string | null;
    screenLayoutId?: number | null;
    template?: Payload | null;
    frameLayoutId?: number | null;
    layoutPath?: string | null;
    frameTemplate?: unknown | null;
    screenType?: string | null;
    supportsConfigPayloads: boolean;
    supportsSensorPayloads: boolean;
    supportsStopPayloads: boolean;
    useKeepAlive?: boolean | null;
}

export interface Collector {
    id: number;
    name: string;
    collectorType: string;
    status: string;
    securityStatus: string;
    description?: string | null;
    url?: string | null;
    externalAccessToken: boolean;
    pollRate?: number | null;
    sendRate?: number | null;
    serviceId?: number | null;
    accessToken?: string | null;
    accessTokenStatus: string;
    lastTested?: string | null;
    testFrequency?: number | null;
    lastFetchErrorMessage?: string | null;
    addedSensorCount: number;
}

export interface Junction {
    id: number;
    name: string;
    description: string;
    type: string;
    status: string;
    sortOrder: number;
    showOnDashboard: boolean;
    autoStartOnLaunch: boolean;
    cronExpression?: string | null;
    allTargetsAllData: boolean;
    allTargetsAllScreens: boolean;
    compressPayload: boolean;
    timezone?: string | null;
    gatewayDeviceId?: number | null;
    gatewayDestination?: string | null;
    destinationOverride?: string | null;
    broadcastPort?: number | null;
    broadcastRate?: number | null;
    baudRate?: number | null;
    mqttBrokerId?: number | null;
    selectedPayloadAttributes: string;
    streamAutoTimeout: boolean;
    streamAutoTimeoutMs: number;
    retryCount: number;
    retryIntervalMs: number;
    enableTests: boolean;
    enableHealthCheck: boolean;
    healthCheckIntervalMs: number;
    allowStartOnCollectorTestFailure: boolean;
    sendConfigPayload: boolean;
    sendSensorPayloads: boolean;
    sendStopPayload: boolean;
    enableNotifications: boolean;
    renderingMode: string;
    streamingJpegQuality: number;
    deviceLinks: JunctionDeviceLink[];
    collectorLinks: JunctionCollectorLink[];
    clonedSensors: Sensor[];
    deviceScreens: DeviceScreen[];
    logic: JunctionLogic[];
    notifications: JunctionNotification[];
    junctionSensorTargets: JunctionSensorTarget[];
    selectedPayloadAttributesList: string[];
}

export interface Service {
    id: number;
    name: string;
    description: string;
    type: string;
    status: string;
    uniqueIdentifier: string;
    comPort?: string | null;
    serviceModel?: string | null;
    serviceManufacturer?: string | null;
    firmwareVersion?: string | null;
    mcu?: string | null;
    wirelessConnectivity?: string | null;
    url?: string | null;
    isGateway: boolean;
    gatewayId?: number | null;
    isJunctionRelayService: boolean;
    lastUpdated: string;
    lastPolled?: string | null;
    pollRate?: number | null;
    sendRate?: number | null;
    accessToken?: string | null;
    externalAccessToken: boolean;
    hasAccessToken: boolean;
    homeAssistantSharedJunctions?: string | null;
    mqttBrokerAddress?: string | null;
    mqttBrokerPort?: string | null;
    mqttUsername?: string | null;
    grafanaSharedMetrics?: string | null;
    sensors: Sensor[];
    peers: DeviceRecord[];
}

export interface JunctionDeviceLink {
    id: number;
    junctionId: number;
    deviceId: number;
    role: string;
    isSelected: boolean;
    isTested: boolean;
    warnOnDuplicate: boolean;
    pollRateOverride?: number | null;
    lastPolled?: string | null;
    sendRateOverride?: number | null;
    lastSent?: string | null;
    declareFailedAfter: number;
    retryAttempts: number;
    deviceName?: string | null;
    deviceDescription?: string | null;
    deviceStatus?: string | null;
    devicePollRate?: number | null;
    deviceSendRate?: number | null;
    screenLayouts: JunctionScreenLayout[];
}

export interface JunctionCollectorLink {
    id: number;
    junctionId: number;
    collectorId: number;
    role: string;
    isSelected: boolean;
    isTested: boolean;
    warnOnDuplicate: boolean;
    pollRateOverride?: number | null;
    lastPolled?: string | null;
    sendRateOverride?: number | null;
    lastSent?: string | null;
    declareFailedAfter: number;
    retryAttempts: number;
    collectorName?: string | null;
    collectorDescription?: string | null;
    collectorStatus?: string | null;
    collectorPollRate?: number | null;
    collectorSendRate?: number | null;
}

export interface JunctionSensorTarget {
    id: number;
    junctionId: number;
    sensorId: number;
    deviceId: number;
    screenId?: number | null;
    positionIndex?: number | null;
}

export interface EventRule {
    id: number;
    name: string;
    description?: string | null;
    enabled: boolean;
    triggerLogic: string;
    lastTriggered?: string | null;
    triggerCount: number;
    createdAt: string;
    updatedAt: string;
    triggers: EventTrigger[];
    actions: EventAction[];
}

export interface Payload {
    id: number;
    displayName?: string | null;
    description?: string | null;
    layoutType: string;
    customLayoutType?: string | null;
    includePrefixConfig: boolean;
    includePrefixSensor: boolean;
    rows?: number | null;
    columns?: number | null;
    jsonLayoutConfig?: string | null;
    isTemplate: boolean;
    isDraft: boolean;
    isPublished: boolean;
    created: string;
    lastModified?: string | null;
    createdBy?: string | null;
    version?: string | null;
    topMargin: number;
    bottomMargin: number;
    leftMargin: number;
    rightMargin: number;
    outerPadding: number;
    innerPadding: number;
    backgroundColor?: string | null;
    borderColor?: string | null;
    borderVisible?: boolean | null;
    borderThickness?: number | null;
    roundedCorners?: boolean | null;
    borderRadiusSize?: number | null;
    opacityPercentage?: number | null;
    gradientDirection?: string | null;
    gradientEndColor?: string | null;
    chartOutlineVisible?: boolean | null;
    showLegend?: boolean | null;
    positionLegendInside?: boolean | null;
    showXAxisLabels?: boolean | null;
    showYAxisLabels?: boolean | null;
    gridDensity?: number | null;
    historyPointsToShow?: number | null;
    chartScrollSpeed?: number | null;
    showUnits?: boolean | null;
    textColor?: string | null;
    textSize?: string | null;
    labelSize?: string | null;
    valueSize?: string | null;
    decimalPlaces?: number | null;
    justifyContent?: string | null;
    alignItems?: string | null;
    textAlignment?: string | null;
    animationType?: string | null;
    animationDuration?: number | null;
    showPreview: boolean;
    previewHeight?: number | null;
    previewWidth?: number | null;
    previewSensors?: number | null;
    isResponsive: boolean;
    mobileLayoutBehavior?: string | null;
    themeId?: number | null;
    inheritThemeStyles: boolean;
    allowInteraction: boolean;
    onClickBehavior?: string | null;
    navigationTarget?: string | null;
    dataRefreshIntervalSeconds?: number | null;
    cacheData: boolean;
    dataFilterCriteria?: string | null;
    backgroundImageUrl?: string | null;
    backgroundImageId?: string | null;
    imageFit?: string | null;
    lazyLoad: boolean;
    renderPriority?: number | null;
    enableScrollbars: boolean;
    minWidth?: number | null;
    maxWidth?: number | null;
    minHeight?: number | null;
    maxHeight?: number | null;
    fieldsToSend?: string | null;
}

export interface JunctionScreenLayout {
    id: number;
    junctionId: number;
    junctionDeviceLinkId: number;
    deviceScreenId: number;
    screenLayoutId?: number | null;
    frameLayoutId?: number | null;
    layoutPath?: string | null;
    targetPollRate?: number | null;
    lastRequested?: string | null;
    onlySendIfChanged: boolean;
    enableUrlAccess: boolean;
    urlPath?: string | null;
    streamingFps?: number | null;
    streamingJpegQuality?: number | null;
}

export interface DeviceCapabilities {
    hasOnboardScreen: boolean;
    hasOnboardLED: boolean;
    hasOnboardRGBLED: boolean;
    hasExternalNeopixels: boolean;
    hasExternalMatrix: boolean;
    hasExternalI2CDevices: boolean;
    hasButtons: boolean;
    hasBattery: boolean;
    supportsEthernet: boolean;
    supportsWiFi: boolean;
    supportsBLE: boolean;
    supportsUSB: boolean;
    supportsHTTP: boolean;
    supportsESPNow: boolean;
    supportsMQTT: boolean;
    supportsWebSockets: boolean;
    hasSpeaker: boolean;
    hasMicroSD: boolean;
    i2cDevices?: unknown[] | null;
    isGateway: boolean;
    screens: unknown[];
}

export interface DeviceI2CDevice {
    id: number;
    deviceId: number;
    i2CAddress: string;
    deviceType: string;
    communicationProtocol: string;
    isEnabled: boolean;
    dateAdded: string;
    endpoints: DeviceI2CDeviceEndpoint[];
}

export interface FrameLayoutSummary {
    id: string;
    displayName: string;
    description?: string | null;
    layoutType: string;
    isTemplate: boolean;
    cloudTemplateId?: string | null;
    cloudVariantId?: string | null;
    isDraft: boolean;
    isPublished: boolean;
    isStandalone: boolean;
    width?: number | null;
    height?: number | null;
    orientation: string;
    backgroundType: string;
    backgroundColor?: string | null;
    backgroundImageUrl?: string | null;
    backgroundImageFit?: string | null;
    backgroundVideoUrl?: string | null;
    backgroundVideoFit?: string | null;
    videoLoop: boolean;
    videoMuted: boolean;
    videoAutoplay: boolean;
    backgroundLoopCompensation?: boolean | null;
    backgroundLoopCutoverMs?: number | null;
    backgroundLoopCrossfadeMs?: number | null;
    backgroundOpacity: number;
    riveFile?: string | null;
    jsonFrameConfig?: string | null;
    jsonFrameConfigRuntime?: string | null;
    jsonFrameElements?: string | null;
    created: string;
    lastModified?: string | null;
    hasThumbnail: boolean;
    thumbnailPath?: string | null;
    thumbnailGeneratedAt?: string | null;
    thumbnailOverride: boolean;
    cloudSnapshotCount: number;
    totalAssetSize: number;
}

export interface DeviceInfo {
    deviceModel?: string | null;
    deviceManufacturer?: string | null;
    firmwareVersion?: string | null;
    customFirmware?: boolean | null;
    mcu?: string | null;
    wirelessConnectivity?: string | null;
    flash?: string | null;
    psram?: string | null;
    uniqueIdentifier?: string | null;
}

export interface LayoutSubscription {
    id: number;
    serverUrl: string;
    serverPort: string;
    serverName?: string | null;
    remoteLayoutId: string;
    remoteLayoutName: string;
    remoteVariantId?: string | null;
    localFilePath: string;
    localFileName: string;
    lastDownloadedAt?: string | null;
    remoteLastModified?: string | null;
    subscribedAt: string;
    isActive: number;
    autoUpdate: number;
    isTemplate: number;
    source: string;
    hasThumbnail: number;
    thumbnailPath?: string | null;
    thumbnailFormat?: string | null;
    authorName?: string | null;
    authorUrl?: string | null;
    authorId?: string | null;
    authorAvatarUrl?: string | null;
}

export interface DeviceRecord {
    id: number;
    name: string;
    description: string;
    type: string;
    status: string;
    uniqueIdentifier: string;
    connMode?: string | null;
    comPort?: string | null;
    baudRate?: number | null;
    deviceModel?: string | null;
    deviceManufacturer?: string | null;
    firmwareVersion?: string | null;
    hasCustomFirmware: boolean;
    ignoreUpdates: boolean;
    mcu?: string | null;
    wirelessConnectivity?: string | null;
    flash?: string | null;
    psram?: string | null;
    isConnected: boolean;
    ipAddress?: string | null;
    hasMQTTConfig: boolean;
    httpPort?: number | null;
    webSocketPort?: number | null;
    mqttPort?: number | null;
    hostname?: string | null;
    isGateway: boolean;
    gatewayId?: number | null;
    isJunctionRelayDevice: boolean;
    isCloudDevice: boolean;
    cloudDeviceId?: number | null;
    lastEncryptedSensorData?: string | null;
    lastHealthReportAt?: string | null;
    createdAt?: string | null;
    lastHealthAlertSent?: string | null;
    lastHealthReminderSent?: string | null;
    pushNotifications: boolean;
    syncMode?: string | null;
    lastUpdated: string;
    sensors: Sensor[];
    peers: DeviceRecord[];
    pollRate?: number | null;
    sendRate?: number | null;
    sshUsername?: string | null;
    sshPassword?: string | null;
    externalSshPassword: boolean;
    sshPort?: number | null;
    sshTimeoutMs?: number | null;
    sshPrivateKey?: string | null;
    externalSshPrivateKey: boolean;
    useSshKeyAuth: boolean;
    sshConnectionRetries?: number | null;
    sshVerifyHostKey: boolean;
    heartbeatProtocol?: string | null;
    heartbeatTarget?: string | null;
    heartbeatExpectedValue?: string | null;
    heartbeatEnabled: boolean;
    heartbeatIntervalMs?: number | null;
    heartbeatGracePeriodMs?: number | null;
    heartbeatMaxRetryAttempts?: number | null;
    useStreamAsHeartbeat: boolean;
    streamHeartbeatThresholdMs?: number | null;
    connectionStatusEnabled: boolean;
    connectionStatusIntervalMs?: number | null;
    lastConnectionStatusCheck?: string | null;
    lastPingAttempt?: string | null;
    lastPinged?: string | null;
    lastPingStatus?: string | null;
    lastPingDurationMs?: number | null;
    consecutivePingFailures?: number | null;
    configLastAppliedAt?: string | null;
    sensorPayloadLastAckAt?: string | null;
    hasOnboardScreen: boolean;
    hasOnboardLED: boolean;
    hasOnboardRGBLED: boolean;
    hasExternalNeopixels: boolean;
    hasExternalMatrix: boolean;
    hasExternalI2CDevices: boolean;
    hasButtons: boolean;
    hasBattery: boolean;
    supportsEthernet: boolean;
    supportsWiFi: boolean;
    supportsBLE: boolean;
    supportsUSB: boolean;
    supportsESPNow: boolean;
    supportsHTTP: boolean;
    supportsMQTT: boolean;
    supportsWebSockets: boolean;
    hasSpeaker: boolean;
    hasMicroSD: boolean;
    isXSD: boolean;
    linkedCollectorId?: number | null;
    screens: DeviceScreen[];
    i2cDevices: DeviceI2CDevice[];
}

export interface JunctionLogic {
    id: number;
    logicName?: string | null;
    description?: string | null;
    junctionId?: number | null;
    sensorId: number;
    conditions: unknown[];
    overrideColorHex?: string | null;
    overrideDisplayText?: string | null;
    hideSensorValue?: boolean | null;
    overrideUnits?: string | null;
    priority?: number | null;
    isEnabled: boolean;
    appliesWhen?: string | null;
}

export interface JunctionNotification {
    id: string;
    type: string;
    message: string;
    title?: string | null;
    category: string;
    duration?: number | null;
    persistent: boolean;
    createdAt: string;
    isDelivered: boolean;
    deliveredAt?: string | null;
    expiresAt?: string | null;
    structuredContent?: string | null;
}

export interface EventTrigger {
    id: number;
    eventRuleId: number;
    triggerOrder: number;
    isActive: boolean;
    triggerType: string;
    triggerSensorId?: number | null;
    triggerCondition?: string | null;
    triggerValue?: string | null;
    triggerDebounceMs: number;
    createdAt: string;
}

export interface EventAction {
    id: number;
    eventRuleId: number;
    actionOrder: number;
    isActive: boolean;
    delayBeforeNextMs: number;
    actionType: string;
    actionTargetSensorId?: number | null;
    actionStaticValue?: string | null;
    actionTransform?: string | null;
    actionJunctionId?: number | null;
    actionMqttTopic?: string | null;
    actionMqttPayload?: string | null;
    actionMqttServiceId?: number | null;
    actionHttpUrl?: string | null;
    actionHttpMethod?: string | null;
    actionHttpPayload?: string | null;
    createdAt: string;
}

export interface DeviceI2CDeviceEndpoint {
    id: number;
    i2CDeviceId: number;
    endpointType: string;
    address: string;
    qoS: number;
    notes?: string | null;
}

export interface DevicePreferencesRecord {
    connMode: string;
    wifiSSID: string;
    wifiPassword: string;
    mqttBroker: string;
    mqttUsername: string;
    mqttPassword: string;
    rotation: number;
    swapBlueGreen?: boolean | null;
    restart?: boolean | null;
    externalNeoPixelsData1?: string | null;
    externalNeoPixelsData2?: string | null;
}

